class Autogenerated {
  bool? success;
  List<ZoneModel>? data;
  String? message;

  Autogenerated({this.success, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      data = <ZoneModel>[];
      json['data'].forEach((v) {
        data!.add(new ZoneModel.fromJson(v));
      });
    }
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    return data;
  }
}

class ZoneModel {
  int? id;
  String? zoneName;
  int? participantsCount;
  int? zoneId;
  int? hostCityId;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;
  String? hostCity;
  String? url;
  bool? isSelected = false;

  ZoneModel(
      {this.id,
      this.zoneName,
      this.participantsCount,
      this.zoneId,
      this.hostCityId,
      this.deletedAt,
      this.createdAt,
      this.updatedAt,
      this.hostCity,
      this.url,
      this.isSelected = false});

  ZoneModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    zoneName = json['zone_name'];
    participantsCount = json['participants_count'];
    zoneId = json['zone_id'];
    hostCityId = json['host_city_id'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    hostCity = json['host_city'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['zone_name'] = this.zoneName;
    data['participants_count'] = this.participantsCount;
    data['zone_id'] = this.zoneId;
    data['host_city_id'] = this.hostCityId;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['host_city'] = this.hostCity;
    data['url'] = this.url;
    return data;
  }
}

class PostData {
  int? id;
  int? postId;
  int? zoneId;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;
  User? user;
  Zone? zone;
  Post? post;

  PostData(
      {this.id,
      this.postId,
      this.zoneId,
      this.deletedAt,
      this.createdAt,
      this.updatedAt,
      this.user,
      this.zone,
      this.post});

  PostData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    postId = json['post_id'];
    zoneId = json['zone_id'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
    zone = json['zone'] != null ? new Zone.fromJson(json['zone']) : null;
    post = json['post'] != null ? new Post.fromJson(json['post']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['post_id'] = this.postId;
    data['zone_id'] = this.zoneId;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    if (this.zone != null) {
      data['zone'] = this.zone!.toJson();
    }
    if (this.post != null) {
      data['post'] = this.post!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? name;
  String? businessName;
  String? city;
  String? address;
  String? mobileNo;
  String? altMobileNo;
  String? email;
  String? profilePhoto;
  String? bio;
  String? role;
  String? emailVerifiedAt;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;

  User(
      {this.id,
      this.name,
      this.businessName,
      this.city,
      this.address,
      this.mobileNo,
      this.altMobileNo,
      this.email,
      this.profilePhoto,
      this.bio,
      this.role,
      this.emailVerifiedAt,
      this.deletedAt,
      this.createdAt,
      this.updatedAt});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    businessName = json['business_name'];
    city = json['city'];
    address = json['address'];
    mobileNo = json['mobile_no'];
    altMobileNo = json['alt_mobile_no'];
    email = json['email'];
    profilePhoto = json['url'];
    bio = json['bio'];
    role = json['role'];
    emailVerifiedAt = json['email_verified_at'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['business_name'] = this.businessName;
    data['city'] = this.city;
    data['address'] = this.address;
    data['mobile_no'] = this.mobileNo;
    data['alt_mobile_no'] = this.altMobileNo;
    data['email'] = this.email;
    data['url'] = this.profilePhoto;
    data['bio'] = this.bio;
    data['role'] = this.role;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Zone {
  int? id;
  String? zoneName;
  int? hostCityId;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;

  Zone(
      {this.id,
      this.zoneName,
      this.hostCityId,
      this.deletedAt,
      this.createdAt,
      this.updatedAt});

  Zone.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    zoneName = json['zone_name'];
    hostCityId = json['host_city_id'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['zone_name'] = this.zoneName;
    data['host_city_id'] = this.hostCityId;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Post {
  int? id;
  String? dsc;
  String? postImage;
  String? title;
  String? likes;
  int? islike;
  String? comments;
  String? type;
  String? status;
  int? userId;
  int? isDeletable;
  String? zoneId;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;

  Post(
      {this.id,
      this.dsc,
      this.postImage,
      this.title,
      this.likes,
      this.islike,
      this.isDeletable,
      this.comments,
      this.type,
      this.status,
      this.userId,
      this.zoneId,
      this.deletedAt,
      this.createdAt,
      this.updatedAt});

  Post.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    dsc = json['dsc'];
    postImage = json['post_image'];
    title = json['title'];
    likes = json['likes'];
    isDeletable = json['is_deletable'];
    islike = json['is_like'];
    comments = json['comments'];
    type = json['type'];
    status = json['status'];
    userId = json['user_id'];
    zoneId = json['zone_id'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['dsc'] = this.dsc;
    data['post_image'] = this.postImage;
    data['title'] = this.title;
    data['likes'] = this.likes;
    data['is_like'] = this.islike;
    data['is_deletable'] = this.isDeletable;
    data['comments'] = this.comments;
    data['type'] = this.type;
    data['status'] = this.status;
    data['user_id'] = this.userId;
    data['zone_id'] = this.zoneId;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class MemberModel {
  int? id;
  String? name;
  String? businessName;
  String? city;
  String? address;
  String? mobileNo;
  String? altMobileNo;
  String? email;
  String? profilePhoto;
  String? bio;
  String? role;
  String? emailVerifiedAt;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;
  UserZone? userZone;

  MemberModel(
      {this.id,
      this.name,
      this.businessName,
      this.city,
      this.address,
      this.mobileNo,
      this.altMobileNo,
      this.email,
      this.profilePhoto,
      this.bio,
      this.role,
      this.emailVerifiedAt,
      this.deletedAt,
      this.createdAt,
      this.updatedAt,
      this.userZone});

  MemberModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    businessName = json['business_name'];
    city = json['city'];
    address = json['address'];
    mobileNo = json['mobile_no'];
    altMobileNo = json['alt_mobile_no'];
    email = json['email'];
    profilePhoto = json['url'];
    bio = json['bio'];
    role = json['role'];
    emailVerifiedAt = json['email_verified_at'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    userZone = json['user_zone'] != null
        ? new UserZone.fromJson(json['user_zone'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['business_name'] = this.businessName;
    data['city'] = this.city;
    data['address'] = this.address;
    data['mobile_no'] = this.mobileNo;
    data['alt_mobile_no'] = this.altMobileNo;
    data['email'] = this.email;
    data['url'] = this.profilePhoto;
    data['bio'] = this.bio;
    data['role'] = this.role;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.userZone != null) {
      data['user_zone'] = this.userZone!.toJson();
    }
    return data;
  }
}

class UserZone {
  int? id;
  int? userId;
  int? zoneDivisionId;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;
  ZoneDivision? zoneDivision;

  UserZone(
      {this.id,
      this.userId,
      this.zoneDivisionId,
      this.deletedAt,
      this.createdAt,
      this.updatedAt,
      this.zoneDivision});

  UserZone.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    zoneDivisionId = json['zone_division_id'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    zoneDivision = json['zone_division'] != null
        ? new ZoneDivision.fromJson(json['zone_division'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['zone_division_id'] = this.zoneDivisionId;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.zoneDivision != null) {
      data['zone_division'] = this.zoneDivision!.toJson();
    }
    return data;
  }
}

class ZoneDivision {
  int? id;
  String? zoneDivisionName;
  int? zoneId;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;

  ZoneDivision(
      {this.id,
      this.zoneDivisionName,
      this.zoneId,
      this.deletedAt,
      this.createdAt,
      this.updatedAt});

  ZoneDivision.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    zoneDivisionName = json['zone_division_name'];
    zoneId = json['zone_id'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['zone_division_name'] = this.zoneDivisionName;
    data['zone_id'] = this.zoneId;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}


class FeedPostLike {
  int? id;
  int? postId;
  int? userId;
  String? createdAt;
  String? updatedAt;
  User? user;

  FeedPostLike(
      {this.id,
        this.postId,
        this.userId,
        this.createdAt,
        this.updatedAt,
        this.user});

  FeedPostLike.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    postId = json['post_id'];
    userId = json['user_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['post_id'] = this.postId;
    data['user_id'] = this.userId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}
